<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GBBassetManagementSystem.Data\GBBassetManagementSystem.Data.csproj" />
    <ProjectReference Include="..\GBBassetManagementSystem.Entity\GBBassetManagementSystem.Entity.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
